version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports: "8888"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    network_mode: "host"

volumes:
  pgadmin-data:
