version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    network_mode: 'host'

volumes:
  pgadmin-data:
